// Generated by `drizzle-kit pull` against the Alembic-owned dev Supabase Postgres DB
// (2026-08-03, revision 0018_node_wave0_tables) — introspection only, never edit the
// column shapes by hand; re-run `npx drizzle-kit pull` and diff instead.
//
// Fidelity gap fixed by hand: drizzle-kit pull rendered
// `feedbackPromptState.runId`'s empty-string default as the invalid TypeScript
// `.default(')` (dropped a quote) instead of `.default('')`. The DB column really is
// `NOT NULL DEFAULT ''` (see mylibrary/db.py FeedbackPromptState.run_id). Fixed below;
// re-check this specific field if the schema is ever re-pulled.
import { pgTable, varchar, index, serial, text, json, doublePrecision, timestamp, uniqueIndex, unique, integer, date, boolean, foreignKey, jsonb, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const alembicVersion = pgTable("alembic_version", {
	versionNum: varchar("version_num", { length: 32 }).primaryKey().notNull(),
});

export const tasteTraits = pgTable("taste_traits", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	claim: text().notNull(),
	polarity: varchar().notNull(),
	exhibits: json(),
	contrasts: json(),
	inferenceConfidence: doublePrecision("inference_confidence").notNull(),
	status: varchar().notNull(),
	userNote: text("user_note"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	userWeight: doublePrecision("user_weight").default(sql`'1'`).notNull(),
	verdictUpdatedAt: timestamp("verdict_updated_at", { mode: 'string' }),
	revealLine: text("reveal_line"),
}, (table) => [
	index("ix_taste_traits_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const profileMeta = pgTable("profile_meta", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	lastProfiledAt: timestamp("last_profiled_at", { mode: 'string' }),
	lastProfileKind: varchar("last_profile_kind"),
	recFeedbackUpdatedAt: timestamp("rec_feedback_updated_at", { mode: 'string' }),
	enrichmentCorrectedAt: timestamp("enrichment_corrected_at", { mode: 'string' }),
}, (table) => [
	uniqueIndex("ix_profile_meta_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const books = pgTable("books", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	goodreadsBookId: varchar("goodreads_book_id"),
	title: varchar().notNull(),
	author: varchar(),
	additionalAuthors: varchar("additional_authors"),
	isbn13: varchar(),
	exclusiveShelf: varchar("exclusive_shelf"),
	goodreadsRating: integer("goodreads_rating").notNull(),
	appRating: integer("app_rating"),
	appReview: text("app_review"),
	feedbackUpdatedAt: timestamp("feedback_updated_at", { mode: 'string' }),
	dateRead: date("date_read"),
	dateAdded: date("date_added"),
	pageCount: integer("page_count"),
	yearPublished: integer("year_published"),
	source: varchar().notNull(),
	excludeFromProfile: boolean("exclude_from_profile").default(false).notNull(),
	isFavorite: boolean("is_favorite").default(false).notNull(),
}, (table) => [
	index("ix_books_exclusive_shelf").using("btree", table.exclusiveShelf.asc().nullsLast().op("text_ops")),
	index("ix_books_goodreads_book_id").using("btree", table.goodreadsBookId.asc().nullsLast().op("text_ops")),
	index("ix_books_isbn13").using("btree", table.isbn13.asc().nullsLast().op("text_ops")),
	index("ix_books_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	unique("uq_book_user_goodreads").on(table.userId, table.goodreadsBookId),
]);

export const userSettings = pgTable("user_settings", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	anthropicApiKeyEncrypted: text("anthropic_api_key_encrypted"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	displayName: varchar("display_name"),
}, (table) => [
	uniqueIndex("ix_user_settings_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const recommendations = pgTable("recommendations", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	runId: varchar("run_id").notNull(),
	rank: integer().notNull(),
	title: varchar().notNull(),
	author: varchar(),
	year: integer(),
	isbn13: varchar(),
	coverUrl: varchar("cover_url"),
	subjects: json(),
	catalogSource: varchar("catalog_source"),
	catalogId: varchar("catalog_id"),
	retrievalPool: varchar("retrieval_pool"),
	seedReason: varchar("seed_reason"),
	score: doublePrecision().notNull(),
	rationale: text(),
	groundedTraitIds: json("grounded_trait_ids"),
	groundedBookIds: json("grounded_book_ids"),
	status: varchar().notNull(),
	userNote: text("user_note"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	description: text(),
	rejectReasons: json("reject_reasons"),
}, (table) => [
	index("ix_recommendations_run_id").using("btree", table.runId.asc().nullsLast().op("text_ops")),
	index("ix_recommendations_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const tasteSignal = pgTable("taste_signal", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	direction: varchar().notNull(),
	targetKind: varchar("target_kind").notNull(),
	targetBookId: integer("target_book_id"),
	snapshot: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
	index("ix_taste_signal_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const enrichment = pgTable("enrichment", {
	id: serial().primaryKey().notNull(),
	bookId: integer("book_id").notNull(),
	resolvedSource: varchar("resolved_source"),
	resolvedId: varchar("resolved_id"),
	subjects: json(),
	series: varchar(),
	seriesPosition: varchar("series_position"),
	description: text(),
	coverUrl: varchar("cover_url"),
	resolutionConfidence: doublePrecision("resolution_confidence").notNull(),
	confidenceLabel: varchar("confidence_label"),
	matchMethod: varchar("match_method"),
	rawResponse: json("raw_response"),
	resolvedAt: timestamp("resolved_at", { mode: 'string' }).defaultNow().notNull(),
	language: varchar(),
}, (table) => [
	uniqueIndex("ix_enrichment_book_id").using("btree", table.bookId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.bookId],
			foreignColumns: [books.id],
			name: "enrichment_book_id_fkey"
		}),
]);

export const enrichJobs = pgTable("enrich_jobs", {
	id: serial().primaryKey().notNull(),
	jobId: varchar("job_id").notNull(),
	userId: varchar("user_id").default('local').notNull(),
	status: varchar().default('pending').notNull(),
	progress: integer().default(0).notNull(),
	total: integer().default(0).notNull(),
	startedAt: timestamp("started_at", { mode: 'string' }),
	finishedAt: timestamp("finished_at", { mode: 'string' }),
	error: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("ix_enrich_jobs_job_id").using("btree", table.jobId.asc().nullsLast().op("text_ops")),
	index("ix_enrich_jobs_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const readerArchetypes = pgTable("reader_archetypes", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	code: varchar().notNull(),
	archetypeName: varchar("archetype_name").notNull(),
	archetypeTagline: text("archetype_tagline").notNull(),
	axisLens: doublePrecision("axis_lens").notNull(),
	axisEngine: doublePrecision("axis_engine").notNull(),
	axisRange: doublePrecision("axis_range").notNull(),
	axisResonance: doublePrecision("axis_resonance").notNull(),
	lensRationale: text("lens_rationale"),
	engineRationale: text("engine_rationale"),
	rangeRationale: text("range_rationale"),
	resonanceRationale: text("resonance_rationale"),
	derivedAt: timestamp("derived_at", { mode: 'string' }).notNull(),
}, (table) => [
	unique("uq_reader_archetype_user").on(table.userId),
]);

export const invites = pgTable("invites", {
	id: serial().primaryKey().notNull(),
	email: varchar().notNull(),
	invitedBy: varchar("invited_by").notNull(),
	supabaseUserId: varchar("supabase_user_id"),
	status: varchar().default('pending').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	acceptedAt: timestamp("accepted_at", { mode: 'string' }),
	revokedAt: timestamp("revoked_at", { mode: 'string' }),
}, (table) => [
	index("ix_invites_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	index("ix_invites_supabase_user_id").using("btree", table.supabaseUserId.asc().nullsLast().op("text_ops")),
]);

export const usageEvents = pgTable("usage_events", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	model: varchar().notNull(),
	operation: varchar().notNull(),
	inputTokens: integer("input_tokens").default(0),
	outputTokens: integer("output_tokens").default(0),
	cacheCreationInputTokens: integer("cache_creation_input_tokens").default(0),
	cacheReadInputTokens: integer("cache_read_input_tokens").default(0),
	costUsd: doublePrecision("cost_usd").default(sql`'0'`),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
	index("ix_usage_events_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamp_ops")),
	index("ix_usage_events_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const feedback = pgTable("feedback", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	category: varchar().notNull(),
	body: text().notNull(),
	trigger: varchar(),
	runId: varchar("run_id"),
	page: varchar(),
	appVersion: varchar("app_version"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ix_feedback_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const feedbackPromptState = pgTable("feedback_prompt_state", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	trigger: varchar().notNull(),
	runId: varchar("run_id").default('').notNull(),
	status: varchar().notNull(),
	snoozeUntil: timestamp("snooze_until", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("uq_feedback_prompt_state").on(table.userId, table.trigger, table.runId),
]);

export const userDirective = pgTable("user_directive", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").default('local').notNull(),
	nlText: text("nl_text"),
	constraints: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
}, (table) => [
	uniqueIndex("ix_user_directive_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const catalogCache = pgTable("catalog_cache", {
	cacheKey: varchar("cache_key").primaryKey().notNull(),
	source: varchar().notNull(),
	payload: jsonb().notNull(),
	fetchedAt: timestamp("fetched_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
});

export const appConfig = pgTable("app_config", {
	key: varchar().primaryKey().notNull(),
	value: jsonb().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
});

export const rateLimits = pgTable("rate_limits", {
	bucketKey: varchar("bucket_key").notNull(),
	windowStart: integer("window_start").notNull(),
	count: integer().default(0).notNull(),
}, (table) => [
	primaryKey({ columns: [table.bucketKey, table.windowStart], name: "rate_limits_pkey"}),
]);
